"""Postgres backups: pg_dump custom-format files in PS_BACKUPS_DIR, pruned after
PS_BACKUP_KEEP_DAYS, and a one-command restore.

What's worth backing up is the database: embeddings and captions took hours of
GPU time; face names, merges and albums are your own work. Thumbnails and crops
are regenerated by `photo-search repair`, eval labels live in git, originals are
your photo library (back that up separately).

In Docker Compose the `backup` service calls this nightly; natively, run
`photo-search db backup` from cron. Both need pg_dump / pg_restore on PATH
(the compose service runs inside the Postgres image, which has them).
"""

from __future__ import annotations

import os
import shutil
import subprocess
import time
from datetime import datetime
from pathlib import Path
from urllib.parse import urlparse

from api.config import get_settings


def _bin(name: str) -> str:
    extra = os.environ.get("PS_PG_BIN_DIR")
    if extra and (Path(extra) / name).exists():
        return str(Path(extra) / name)
    exe = shutil.which(name)
    if not exe:
        raise SystemExit(
            f"{name} not found. Install the PostgreSQL client tools, set PS_PG_BIN_DIR, "
            "or use `make backup` / `make restore`, which run inside the database container."
        )
    return exe


def backup(url: str | None = None, out_dir: Path | None = None) -> Path:
    s = get_settings()
    url = url or s.database_url
    out_dir = out_dir or s.backups_dir
    out_dir.mkdir(parents=True, exist_ok=True)
    name = urlparse(url).path.lstrip("/") or "photos"
    out = out_dir / f"{name}-{datetime.now():%Y%m%d-%H%M%S}.dump"
    tmp = out.with_suffix(".partial")
    subprocess.run(
        [_bin("pg_dump"), "--format=custom", "--compress=6", f"--file={tmp}", url], check=True
    )
    tmp.replace(out)  # a crash mid-dump never leaves a truncated .dump that looks valid
    return out


def prune(out_dir: Path | None = None, keep_days: int | None = None) -> list[Path]:
    s = get_settings()
    out_dir = out_dir or s.backups_dir
    keep_days = s.backup_keep_days if keep_days is None else keep_days
    cutoff = time.time() - keep_days * 86400
    dumps = sorted(out_dir.glob("*.dump"), key=lambda p: p.stat().st_mtime)
    removed = []
    for p in dumps[:-1]:  # never delete the newest backup, however old
        if p.stat().st_mtime < cutoff:
            p.unlink()
            removed.append(p)
    return removed


def list_backups(out_dir: Path | None = None) -> list[tuple[Path, float, float]]:
    out_dir = out_dir or get_settings().backups_dir
    return [
        (p, p.stat().st_size / 1e6, p.stat().st_mtime)
        for p in sorted(out_dir.glob("*.dump"), key=lambda p: p.stat().st_mtime, reverse=True)
    ]


def restore(dump: Path, url: str | None = None) -> None:
    """Replace the database contents with the dump, then apply any newer migrations.
    Stop the API and workers first so nothing writes mid-restore."""
    url = url or get_settings().database_url
    if not dump.exists():
        raise SystemExit(f"no such backup: {dump}")
    from api.db.session import close_pool

    close_pool()
    subprocess.run(
        [
            _bin("pg_restore"),
            "--clean",
            "--if-exists",
            "--no-owner",
            "--single-transaction",
            f"--dbname={url}",
            str(dump),
        ],
        check=True,
    )
    from api.db.migrate import migrate

    migrate(url)
